# Generated by Django 5.2 on 2025-04-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateField()),
                ('client', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(default='Client par défaut', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(default='Client par défaut', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='Client par défaut', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(),
        ),
    ]
