# Generated by Django 5.2 on 2025-04-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_paiement_date_paiement_date_paiement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_date',
        ),
        migrations.AddField(
            model_name='sale',
            name='annee',
            field=models.IntegerField(default='2020'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='chiffre_affaire',
            field=models.FloatField(default=1000.0),
            preserve_default=False,
        ),
    ]
