# Generated by Django 5.2 on 2025-04-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_sale_client_id_remove_sale_price_and_more'),
    ]

    operations = [
    ]
