# Generated by Django 5.2 on 2025-04-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20250417_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='annee',
            field=models.DateField(),
        ),
    ]
