# Generated by Django 5.2 on 2025-04-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_sale_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='annee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='chiffre_affaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
